PRISMA_VERSION: "1.34.10"
FQDN: ""
ENABLE_S3_BACKUP: false
S3_ACCESS_KEY_ID: ""
S3_SECRET_ACCESS_KEY: ""
S3_BUCKET: ""
S3_REGION: "eu-central-1"
S3_ENDPOINT: "https://s3.eu-central-1.wasabisys.com"
BACKUP_SCHEDULE: "0 0 * * *"
STORAGE_CLASS_BOX: ""
INSTALL_INGRESS: true
INSTALL_MYSQL: true
MYSQL_HOST: "mysql"
MYSQL_USER: "root"
MYSQL_PASSWORD: ""
PRISMA_MANAGEMENT_SCHEMA: "prisma"
PRISMA_MANAGEMENT_API_SECRET: ""
